# gen_pragmas.ps1 v5
# Auto-generates winhttp_pragmas.h with ALL 89 export forwarders
# ZERO interception - ALL functions forwarded to winhttp_orig.dll
# Our DLL is 100% transparent + just starts a Python server in DllMain

$systemDll = "C:\Windows\System32\winhttp.dll"
$headerFile = "winhttp_pragmas.h"
$origDll   = "winhttp_orig"

Write-Host "Generating $headerFile from $systemDll ..."

# Run dumpbin to get exports
$dumpOutput = & dumpbin /exports $systemDll 2>&1

# Parse export names - forward ALL of them, no skipping
$exports = @()
foreach ($line in $dumpOutput) {
    if ($line -match '^\s+\d+\s+[0-9A-Fa-f]+\s+[0-9A-Fa-f]+\s+(\S+)\s*$') {
        $funcName = $Matches[1]
        $exports += $funcName
    }
}

if ($exports.Count -eq 0) {
    Write-Host "ERROR: No exports found! Make sure dumpbin is available."
    exit 1
}

# Write header file with pragma forwarders
$lines = @()
$lines += "// Auto-generated by gen_pragmas.ps1"
$lines += "// DO NOT EDIT - regenerated on each build"
$lines += "// ALL $($exports.Count) WinHTTP exports forwarded to $origDll (ZERO interception)"
$lines += ""

foreach ($func in $exports) {
    $lines += ('#pragma comment(linker, "/export:' + $func + '=' + $origDll + '.' + $func + '")')
}

Set-Content -Path $headerFile -Value $lines -Encoding ASCII

Write-Host ""
Write-Host "Generated $headerFile with $($exports.Count) forwarders."
Write-Host "No functions intercepted - 100% transparent proxy"
